### ISSUE TITLE
Problems in executing the cell of OW_tutorial2.ipynb

### ISSUE THREAD

**Issue by ronygolderku** [melhawaii/python-satellite-course#1]
Hello,
I am facing problem to execute the following code:
```
plt.figure(figsize=(12,5)) 
plt.plot(swdates,swAVG,label='sw',c='red',marker='.',linestyle='-')
plt.plot(aqdates,aqAVG,label='aq',c='blue',marker='.',linestyle='-')
plt.plot(snppdates,snppAVG,label='snpp',c='green',marker='.',linestyle='-')
plt.ylabel('Chl-a (mg/m^3)')
plt.legend()
```
The return of execution with errors like

> TypeError: float() argument must be a string or a number, not 'cftime._cftime.DatetimeGregorian'

Please, help me to fix the issues.

Regards,
Rony

**Comment by shospital** [comment]
@ronygolderku 

In the previous cells where you create the date variables using nc.num2date, you need to add two additional flags:
`only_use_python_datetimes=True
`
`only_use_cftime_datetimes=False`

For example:
`aqdates=nc.num2date(aq_ds.time,aq_ds.time.units, only_use_python_datetimes=True, only_use_cftime_datetimes=False)
`

You need to add those two flags for each date variable.  
We will soon update the tutorial.

**Comment by oceanwatch** [comment]
Thanks both, I made the changes to this tutorial.
